"""Common outbox constants."""

from __future__ import annotations

# Max lengths for database fields
LAST_ERROR_MAX_LENGTH = 2000
WORKER_ID_MAX_LENGTH = 255
FORCE_UNLOCK_REASON_MAX_LENGTH = 255
IDEMPOTENCY_KEY_MAX_LENGTH = 128
AGGREGATE_TYPE_MAX_LENGTH = 50
EVENT_TYPE_MAX_LENGTH = 100
TOPIC_MAX_LENGTH = 255
SOURCE_MAX_LENGTH = 255
MESSAGE_ID_MAX_LENGTH = 255
PARTITION_KEY_MAX_LENGTH = 255
TRACE_ID_MAX_LENGTH = 64
CORRELATION_ID_MAX_LENGTH = 64
CAUSATION_ID_MAX_LENGTH = 64
SCHEMA_VERSION_MAX_LENGTH = 50
CONSUMER_GROUP_MAX_LENGTH = 255

# Default behavior
DEFAULT_TRUNCATION_SUFFIX = "... [TRUNCATED]"
DEFAULT_MAX_ATTEMPTS = 6
DEFAULT_SCHEDULE_AT_SKEW_SECONDS = 60
DEFAULT_SCHEDULE_AT_MAX_FUTURE_SECONDS = 365 * 24 * 3600

# Payload and Headers limits
DEFAULT_PAYLOAD_MAX_BYTES = 1_000_000
DEFAULT_HEADERS_MAX_COUNT = 100
DEFAULT_HEADER_KEY_MAX_LENGTH = 64
DEFAULT_HEADER_VALUE_MAX_LENGTH = 512

# Job and processing defaults
DEFAULT_BACKOFF_BASE_SECONDS = 10.0
DEFAULT_BACKOFF_CAP_SECONDS = 3600.0
DEFAULT_PUBLISH_TIMEOUT_SECONDS = 30.0
DEFAULT_PROCESS_TIMEOUT_SECONDS = 30.0
DEFAULT_LEASE_TIMEOUT_SECONDS = 300
DEFAULT_MARK_RESULTS_MAX_RETRIES = 3
DEFAULT_MARK_RESULTS_RETRY_DELAY = 1.0

# Maintenance and Cleanup
DEFAULT_CLEANUP_BATCH_SIZE = 1000
DEFAULT_MAINTENANCE_MAX_ITERATIONS = 10000

# Event skip reasons
REASON_DUPLICATE_SIBLING = "duplicate_sibling"
REASON_IDEMPOTENT_DUPLICATE = "idempotent_duplicate"
